[Feat] 네트워크/인앱 에러시 새로고침 화면 구현
TeamHARA/KAERA_iOS pull request #190
Opened 2024-01-18 18:26 UTC by oy6uns

## 💪 작업한 내용
- 네트워크/인앱 에러시에 서버에 재요청을 보낼 수 있는 새로고침 화면을 구현하였습니다. 

## 💜 PR Point

- appError와 internetError 두 가지 경우를 포함하는 새로운 열거형 ErrorCase를 추가하였습니다. 
- ErrorView에 뷰를 업데이트하는 modifyType 메소드를 구현하고, 버튼 클릭시 errorType에 따라 메소드가 실행되게끔 했습니다. 
- HomeWorryDetailVC에 configureErrorView 메소드를 구현하여 ErrorView의 동작을 관리해주었습니다. 
- HomeAPI에 status별 에러를 분기처리해주었고, HomeWorryDetailViewModel에도 그에 맞게 분기처리를 추가해주었습니다. 

#### 해결 못한 이슈
1. reloadWorryDetail()에서 input.send(worryId) 실행 시에 VM Transform 함수로 안넘어가서 UpdateUI가 제대로 안됨.
-> input.send 실행 후 dataBind만 잘 되면 나머지는 ok
2. 무한 로딩 이슈
-> 로딩바가 사라지지 않고 무한 로딩되는 이슈가 발생

## 📸 스크린샷

수정하고 추가하겠습니다. 

## 🚨 관련 이슈
- Resolved: #180

2024-01-20 16:48 UTC, daminoworld requested changes
생각보다 어려운 이슈였어서 해결하기 진짜 쉽지 않았을텐데 쵝오입니다ㅠ 고생하셨어요 역시 똑똑 흰둥이님...🫡👍🔥💜

2024-01-20 16:48 UTC, daminoworld commented on KAERA/KAERA/Resources/Assets.xcassets/Icons/internet_error.imageset/Contents.json
> +}
internet_error 이미지 singleScale로 바꿔주세용

2024-01-20 16:48 UTC, daminoworld commented on KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
> +        setLayout()
setLayout 호출 시점을 바꾼 이유가 뭔가요?

2024-01-20 16:48 UTC, daminoworld commented on KAERA/KAERA/Scenes/Components/ErrorView.swift
> +    }
각 케이스별세팅을 setAppErroUI, setInternetErrorUI 등의 이름으로 따로 빼면 더 깔끔할 것 같아요~

2024-01-20 16:48 UTC, daminoworld commented on KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
> +        self.view.addSubviews([navigationBarView, bottmContainerView])
diggingLayout에 navigationBarView가 추가된 이유가 뭔가요~? 
setLayout에서 digging, dug(고민 중, 고민 완료) 케이스 공통으로 navigationBarView를 추가 해줘 여기서는 필요가 없을 것 같아용

2024-01-20 16:48 UTC, daminoworld commented on KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
> +        setLayout()
커멘트 남기고 확인해보니까 setLayout()에서 에러뷰가 추가 되는데 기존순서에서는 errorView가 추가되고 setDigginLayout에서 하단 버튼 뷰가 추가되어 에러뷰를 가리는 문제가 생겨서 순서를 바꾸신것 같네요~!

2024-01-20 16:48 UTC, daminoworld commented on KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
> +        setLayout()
일단 테스트 했을때는 문제 없었는데 고민중, 고민 완료 공통으로 들어가는 네비바, 스크롤 뷰가 먼저 추가 되고, 그 이후에 고민 중, 완료에따라 그에 따른 뷰가 위에 추가 되는게 더 자연스러운것 같아서 기존처럼 setLayout -> setDiggingLayout / setDugLayout 으로 가되 에러뷰 레이아웃 코드를 따로 빼서 setErrorViewLayout을 만들어 setLayout -> setDiggingLayout / setDugLayout -> setErrorViewLayout 으로 호출해주는게 어떨까 제안드려봅니다~

2024-01-20 16:48 UTC, daminoworld commented on KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
>          navigationBarView.snp.makeConstraints {
navigationBarView.snp.makeConstraints 코드가 실수로 setLayout이랑 setDiggingLayout에 둘다 들어가 있어서 setDiggingLayout을 먼저 실행 시킨 상태에서 view에 navigationBarView가 추가가 안된 상태라 navigationBarView의 레이아웃 코드에서 에러가 났고, 그래서 setDiggingLayout에서 navigationBarView를 추가 시켜 주신것 같아요..ㅎㅎ
위에 제안한 것처럼 레이아웃 호출 순서를 기존에다가 에러뷰만 추가하는 것으로하고, 여기에 추가 되어있는 navigationBarView는 빼고, setLayout에 navigationBarView.snp.makeConstraints 코드를 잘라내서 setDiggingLayout에 있던 코드로 바꿔 주시면 될 것 같습니다!

2024-01-20 16:48 UTC, daminoworld commented on KAERA/KAERA/Scenes/Home/ViewModel/HomeWorryDetailViewModel.swift
> -            self.worryDetail = data
성공했을때 viewModel에 있는 worryDetail에 data를 저장하는 코드는 살려주셔야 할 것 같아요!

2024-01-20 16:48 UTC, daminoworld commented on KAERA/KAERA/Scenes/Home/ViewModel/HomeWorryDetailViewModel.swift
>              }
Future와 promiss로 잘 해결해주셨네요~!! 저도 공부 좀 더 해봐야겠습니다ㅠ 배워갑니다 쵝오

2024-01-20 16:48 UTC, daminoworld commented on KAERA/KAERA/Scenes/Home/ViewModel/HomeWorryDetailViewModel.swift
>              }
여기서 guard let 구문에서 else로 빠지는 경우는 어떤 경우가 있을까요..?ㅎㅎ

2024-01-20 16:48 UTC, daminoworld commented on KAERA/KAERA/Scenes/Home/ViewModel/HomeWorryDetailViewModel.swift
>              }
flatMap 사용 배워갑니다 쵝오~!!!

2024-01-20 17:35 UTC, daminoworld commented on KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
> +        cancellables = []
구독을 취소할때 cancellable에 빈배열을 넣어서 취소할 수도 있군요 배워갑니다~!!
근데 제가 Future와 Promise에 대해서 좀 봐보니까 Future에서 Promise 클로저로 값을 방출하게 되면 finished가 바로 뜨면서 구독이 자동으로 취소되어 따로 취소할 필요는 없다고 합니다! 그래서 사실 여기서 구독 취소를 할 필요는 없는것 같은데 근데 또 혹시나 구독 취소가 안된게 있을 수 있어서 이렇게 확실히 취소하는것도 나쁘지 않을것도 같고... 성호님 의견이 궁금합니다
<img width="645" alt="image" src="https://github.com/TeamHARA/KAERA_iOS/assets/32871014/f911547d-61ca-4676-8b2a-434288245701">

2024-01-21 09:14 UTC, oy6uns commented on KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
> +        setLayout()
오 요런 디테일,,,항상 생각하면서 코드 짜겠습니다. 하나 또 배워가네요

2024-01-21 09:15 UTC, oy6uns commented on KAERA/KAERA/Scenes/Components/ErrorView.swift
> +    }
넵👍🏻

2024-01-21 09:17 UTC, oy6uns commented on KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
> +        self.view.addSubviews([navigationBarView, bottmContainerView])
errorView 때문에 순서를 조정하다가 넣었던 것 같습니다! 수정했습니다:)

2024-01-21 09:35 UTC, oy6uns reviewed
항상 예리한 지적과 꼼꼼한 검토 정말 감사드립니당🤎

2024-01-21 09:35 UTC, oy6uns commented on KAERA/KAERA/Scenes/Home/ViewModel/HomeWorryDetailViewModel.swift
>              }
안전성을 위해 앱 내부 오류시 코드 구동이 잘 안굴러갈 때를 대비해서 appError를 챗선생이 심어놓은거 같은데,
불필요한 코드인 것 같아서 뺐습니다!

빼도 동작 잘 되는것 같습니다. 저도 다시 보니 굳이 필요가 없을 것 같네용

2024-01-21 09:35 UTC, oy6uns commented on KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
> +        cancellables = []
저도 sink와 send를 사용해서 데이터를 전달했을 시에는 구독취소를 직접 시켜주고, dataBind()를 다시 실행해주면 구독이 정상적으로 될 거 같아서 시행착오 중에 작성했던 코드였는데 

future과 promise 사용 후 구독 취소 및 재등록이 정상적으로 되는 것 같아서 불필요한 코드인 것 같습니다
좋은 지적 감사합니당!

2024-01-21 09:35 UTC, oy6uns commented on KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
> +        cancellables = []
<img width="512" alt="스크린샷 2024-01-21 오후 6 32 58" src="https://github.com/TeamHARA/KAERA_iOS/assets/45239582/fd779db7-d399-4589-a5fc-054dad1911b6">

챗 선생님은 안전성 때문에 그대로 냅두는 것이 좋다고 하는데, flow상의 문제는 없으니 그대로 가는 걸루 할까요~?ㅎㅎ 
@daminoworld 어떠신가용!

2024-01-21 10:00 UTC, daminoworld commented on KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
> +        cancellables = []
네네 좋습니다 챗선생님의 의견 반영해보죠ㅋㅋ

2024-01-21 10:56 UTC, daminoworld commented on KAERA/KAERA/Scenes/Home/ViewModel/HomeWorryDetailViewModel.swift
>              }
guard let 부분은 그냥 질문이였어요ㅎㅎ 제가 보기에 self 에 대해 weak self로  약한 참조를 유지하는게 더 안전해서 기존처럼 guard let을 살리는게 좋을 것 같습니다! 수정은 머지하고 제가 그냥 할게요~!

2024-01-21 10:57 UTC, daminoworld approved these changes

2024-01-21 10:57 UTC, merged