[Feat] 고민작성지 뷰에서 선택한 템플릿의 고민작성뷰 present 구현
TeamHARA/KAERA_iOS pull request #45
Opened 2023-08-31 04:33 UTC by oy6uns

## 💪 작업한 내용
- 고민작성지 뷰에서 선택한 템플릿에 해당하는 고민작성뷰를 present해줍니다. 

## 💜 PR Point

- '작성하러가기' 버튼이 클릭되었을 때 고민작성뷰 instance를 새로 생성하여 present 해주었습니다. 
- 고민작성뷰가 띄어질 때 templateId를 뷰모델로 send해주어 해당 템플릿의 question과 hint 리스트를 받아옵니다. 
- writeVC의 템플릿 title과 템플릿 shortInfo를 받아오는 delegate부분을 사용하여 templateInfoVC에서 writeVC가 띄어질 때, 선택한 템플릿에 해당하는 제목과 설명이 바로 보여질 수 있게끔 하였습니다. 

## 📸 스크린샷

![Simulator Screen Recording - iPhone 13 mini - 2023-08-31 at 13 31 25](https://github.com/TeamHARA/KAERA_iOS/assets/45239582/6b20ad10-c028-4397-9ae7-c39c44f70d4a)

## 🚨 관련 이슈
- Resolved: #44

2023-08-31 12:07 UTC, daminoworld requested changes
구현하느라고 고생하셨어요!! 근데 구현은 되게 잘 하는데 기존의 코드를 잘 안써먹고, 필요한것 마다 새로써서 만드는 느낌이라ㅠ 되도록이면 효율적으로 코드를 써서 구현해봅시다..ㅎㅎ

2023-08-31 12:07 UTC, daminoworld commented on KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
> +        cell.delegate = self
델리게이트 채택 시점 굳

2023-08-31 12:07 UTC, daminoworld commented on KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
> +    }
dataBind 메서드에서 list를 받아서 그거를 updateTV에 넘겨서 templateInfoList에 넣어주고 있으니 templateTitleShortInfoList를 따로 만들필요가 없고  sendTitleInfo 함수를 또 만들어서 구독을 할 필요는 없을 것 같습니다!?ㅎㅎ

2023-08-31 12:07 UTC, daminoworld commented on KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
>          cell.dataBind(model: templateInfoList[indexPath.row])
코드를 보다보니  템플릿 셀에 indexPath 프로퍼티를 따로 쓸 필요가 없을 것 같습니다.
여기dataBind에서 TemplatePublisherModel 타입의 데이터를 셀에게 넘겨주요? 그럼 셀의 dataBind 함수에서 template Id도 셀 내부 프로퍼티에 저장을하고 델리게이트 호출시 그 templateId 프로퍼티를 넘겨주면 되겠죠?

2023-08-31 12:07 UTC, daminoworld commented on KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
>          cell.indexPath = indexPath
No need

2023-08-31 12:07 UTC, daminoworld commented on KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
> +    }
델리게이트로 이 메서드를 실행시켜서 writeVC를 띄우는 것은 좋은데, 여기서 writeVC의 dataBind와 input.send까지 시켜줘야할까요..?  보니까 writeVC의 viewDidLoad에서 dataBind가 이미 실행되어 dataBind를 실행할 필요가 없고, templateId는 writeVC의 생성자 파라미터로 전달하고 writeVC 내부에서 dataBind이후 input.send()가 실행되게 하는거 어떨까요?
writeVC의 init에 dataBind와, templateId 전달 하는것 괜찮아보이네용 
쓰다보니 writeVC의  templateReload함수를 실행시켜주려 하니까 그러면 그냥  writeVC 생성시, templateId 만 넘겨주는게 아니라, 여기 프로퍼티인 templateInfoList를 통째로 넘겨주고 writeVC 내부에서 reload함수를 실행시키게 하는게 좋을 것 같아영

2023-08-31 12:07 UTC, daminoworld commented on KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
>          templateInfoTV.reloadData()
여기서 이미 Template 리스트를 받아오니까 templateTitleShortInfoList 는 필요없지 않을까요?

2023-09-03 08:54 UTC, oy6uns commented on KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
> +    }
음,,,근데 요게 제가 Model을 2종류로 만들었어요! 자세히 보면,,, TemplateListPublisherModel와 TemplateInfoPublisherModel의 2종류랍니다,,,ㅎ
그래서 TemplateInfoPublisherModel에는 shortInfo가 없어서 이렇게 ViewModel과 통신하는 부분을 2개를 만들어야 한답니다 ㅠㅠ
제가 처음부터 다 고려해서 모델 하나만 만들면 좋았겠지만,,,코드가 전체적으로 꼬였네요

2023-09-03 08:59 UTC, oy6uns commented on KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
>          templateInfoTV.reloadData()
요것도 위에서 설명한 대로입니다! ㅎㅎ,,,

2023-09-03 12:38 UTC, daminoworld approved these changes
구욷~

2023-09-04 04:20 UTC, merged